// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSwNfFb7o4LScoFrT7odAgBe-oPfutxg',
    appId: '1:205885533230:web:11da2a7c31970e428f43bf',
    messagingSenderId: '205885533230',
    projectId: 'android-app-82183',
    authDomain: 'android-app-82183.firebaseapp.com',
    storageBucket: 'android-app-82183.appspot.com',
    measurementId: 'G-RTW9RLT5DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNzcd4oIYH3RLEqCOGUD5mHiFrBoWOm4',
    appId: '1:205885533230:android:4d482565d9765b868f43bf',
    messagingSenderId: '205885533230',
    projectId: 'android-app-82183',
    storageBucket: 'android-app-82183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCg5DzsDn6P-jzjAyDJPpe7pCO0EZip8g',
    appId: '1:205885533230:ios:1df9b22cd2a440898f43bf',
    messagingSenderId: '205885533230',
    projectId: 'android-app-82183',
    storageBucket: 'android-app-82183.appspot.com',
    iosClientId: '205885533230-88qlomh6mtk75gragcc2e5obfh2hnnh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.example5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCg5DzsDn6P-jzjAyDJPpe7pCO0EZip8g',
    appId: '1:205885533230:ios:ff8e0484c90c950d8f43bf',
    messagingSenderId: '205885533230',
    projectId: 'android-app-82183',
    storageBucket: 'android-app-82183.appspot.com',
    iosClientId: '205885533230-get1kjludq1j8lkqnli91i66sn43524a.apps.googleusercontent.com',
    iosBundleId: 'com.example.example5.RunnerTests',
  );
}
